// <auto-generated />
using System;
using CloudLens.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudLens.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CloudLens.API.Data.Entities.AISettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiKey")
                        .IsRequired();

                    b.Property<string>("Endpoint");

                    b.Property<int>("MaxTokens");

                    b.Property<string>("Model")
                        .IsRequired();

                    b.Property<string>("Provider")
                        .IsRequired();

                    b.Property<double>("Temperature");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("AISettings");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.CachedAIRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CachedAt");

                    b.Property<string>("Category")
                        .IsRequired();

                    b.Property<string>("ContextHash")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Effort")
                        .IsRequired();

                    b.Property<string>("PotentialSavings");

                    b.Property<string>("Priority")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CachedAt");

                    b.ToTable("CachedAIRecommendations");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.CachedCloudCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountId")
                        .IsRequired();

                    b.Property<string>("AccountName")
                        .IsRequired();

                    b.Property<DateTime>("CachedAt");

                    b.Property<string>("CostsByServiceJson")
                        .IsRequired();

                    b.Property<string>("Currency")
                        .IsRequired();

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("MonthlyCostsJson")
                        .IsRequired();

                    b.Property<string>("Provider")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.Property<decimal>("TotalCost");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CachedAt");

                    b.HasIndex("Provider");

                    b.ToTable("CachedCloudCosts");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.CachedCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CachedAt");

                    b.Property<string>("CostsByServiceJson")
                        .IsRequired();

                    b.Property<string>("Currency")
                        .IsRequired();

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("SubscriptionId")
                        .IsRequired();

                    b.Property<string>("SubscriptionName")
                        .IsRequired();

                    b.Property<decimal>("TotalCost");

                    b.HasKey("Id");

                    b.HasIndex("CachedAt");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("CachedCosts");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.CachedMonthlyCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CachedAt");

                    b.Property<string>("ContextHash")
                        .IsRequired();

                    b.Property<decimal>("Cost");

                    b.Property<string>("Currency")
                        .IsRequired();

                    b.Property<string>("Month")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CachedAt");

                    b.HasIndex("ContextHash");

                    b.ToTable("CachedMonthlyCosts");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.CachedResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CachedAt");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ResourceGroup")
                        .IsRequired();

                    b.Property<string>("ResourceId")
                        .IsRequired();

                    b.Property<string>("SubscriptionId")
                        .IsRequired();

                    b.Property<string>("TagsJson")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CachedAt");

                    b.HasIndex("ResourceId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("CachedResources");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.CachedResourceCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CachedAt");

                    b.Property<string>("ContextHash")
                        .IsRequired();

                    b.Property<string>("MonthlyCostsJson")
                        .IsRequired();

                    b.Property<string>("ResourceGroup")
                        .IsRequired();

                    b.Property<string>("ResourceId")
                        .IsRequired();

                    b.Property<string>("ResourceName")
                        .IsRequired();

                    b.Property<string>("ResourceType")
                        .IsRequired();

                    b.Property<decimal>("TotalCost");

                    b.HasKey("Id");

                    b.HasIndex("CachedAt");

                    b.HasIndex("ContextHash");

                    b.HasIndex("ResourceId");

                    b.ToTable("CachedResourceCosts");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.CredentialSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId")
                        .IsRequired();

                    b.Property<string>("ClientSecret")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("LastAccessedAt");

                    b.Property<string>("SessionId")
                        .IsRequired();

                    b.Property<int>("SubscriptionCount");

                    b.Property<string>("SubscriptionIdsJson")
                        .IsRequired();

                    b.Property<string>("TenantId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CredentialSessions");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.GlobalAwsCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessKeyId")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Region")
                        .IsRequired();

                    b.Property<string>("SecretAccessKey")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("GlobalAwsCredentials");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.GlobalAzureCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId")
                        .IsRequired();

                    b.Property<string>("ClientSecret")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsActive");

                    b.Property<int>("SubscriptionCount");

                    b.Property<string>("SubscriptionIdsJson")
                        .IsRequired();

                    b.Property<string>("SubscriptionNamesJson")
                        .IsRequired();

                    b.Property<string>("TenantId")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("GlobalAzureCredentials");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.GlobalGcpCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsActive");

                    b.Property<string>("ServiceAccountJson")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("GlobalGcpCredentials");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.SsoProviderConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Authority")
                        .HasMaxLength(500);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(255);

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("RedirectUri")
                        .HasMaxLength(500);

                    b.Property<string>("Scopes")
                        .HasMaxLength(1000);

                    b.Property<string>("TenantId")
                        .HasMaxLength(255);

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("SsoProviderConfigs");
                });

            modelBuilder.Entity("CloudLens.API.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastLoginAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(255);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512);

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(128);

                    b.Property<DateTime?>("PasswordResetTokenExpiry");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500);

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("Role");

                    b.Property<string>("TenantId")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CloudLens.API.Models.AuditLogEntry", b =>
                {
                    b.Property<string>("LogId");

                    b.Property<string>("Actor")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EventType")
                        .IsRequired();

                    b.Property<string>("IpAddress")
                        .IsRequired();

                    b.Property<string>("ResourceId")
                        .IsRequired();

                    b.Property<string>("SubscriptionId")
                        .IsRequired();

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("LogId");

                    b.HasIndex("Actor");

                    b.HasIndex("EventType");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CloudLens.API.Models.ComplianceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CompliancePercent");

                    b.Property<string>("ControlId")
                        .IsRequired();

                    b.Property<string>("EvidenceSummaryJson")
                        .IsRequired();

                    b.Property<int>("FailedChecks");

                    b.Property<int>("PassedChecks");

                    b.Property<string>("SnapshotDate")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("SubscriptionId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("SnapshotDate");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("ComplianceSnapshots");
                });

            modelBuilder.Entity("CloudLens.API.Models.CostAlertHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AcknowledgedAt");

                    b.Property<string>("AcknowledgedBy");

                    b.Property<decimal>("ActualAmount");

                    b.Property<int>("AlertRuleId");

                    b.Property<string>("AlertRuleName")
                        .IsRequired();

                    b.Property<string>("Currency")
                        .IsRequired();

                    b.Property<string>("Details")
                        .IsRequired();

                    b.Property<bool>("EmailSent");

                    b.Property<bool>("JiraTicketCreated");

                    b.Property<string>("JiraTicketKey");

                    b.Property<DateTime?>("ResolvedAt");

                    b.Property<string>("ResourceGroup");

                    b.Property<string>("ResourceType");

                    b.Property<string>("ServiceName");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("SubscriptionId")
                        .IsRequired();

                    b.Property<decimal>("ThresholdAmount");

                    b.Property<DateTime>("TriggeredAt");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("Status");

                    b.HasIndex("TriggeredAt");

                    b.ToTable("CostAlertHistory");
                });

            modelBuilder.Entity("CloudLens.API.Models.CostAlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlertType")
                        .IsRequired();

                    b.Property<string>("CheckFrequency")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<string>("Currency")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("IsEnabled");

                    b.Property<DateTime?>("LastCheckedAt");

                    b.Property<DateTime?>("LastTriggeredAt");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NotificationEmail")
                        .IsRequired();

                    b.Property<string>("ResourceGroup");

                    b.Property<string>("ResourceType");

                    b.Property<bool>("SendJiraTicket");

                    b.Property<string>("ServiceName");

                    b.Property<string>("SessionId")
                        .IsRequired();

                    b.Property<string>("SubscriptionId");

                    b.Property<decimal>("ThresholdAmount");

                    b.Property<string>("ThresholdOperator")
                        .IsRequired();

                    b.Property<int>("TriggerCount");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AlertType");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("LastCheckedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("CostAlertRules");
                });

            modelBuilder.Entity("CloudLens.API.Models.JiraSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiToken")
                        .IsRequired();

                    b.Property<string>("DefaultIssueType")
                        .IsRequired();

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("JiraUrl")
                        .IsRequired();

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("ProjectKey")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LastModified");

                    b.ToTable("JiraSettings");
                });

            modelBuilder.Entity("CloudLens.API.Models.RemediationAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionsTaken")
                        .IsRequired();

                    b.Property<DateTime>("AttemptedAt");

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<string>("ErrorMessage");

                    b.Property<int>("IncidentId");

                    b.Property<bool>("IsAutomated");

                    b.Property<string>("PerformedBy");

                    b.Property<string>("RemediationType")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<int>("Tier");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Status");

                    b.HasIndex("Tier");

                    b.ToTable("RemediationAttempts");
                });

            modelBuilder.Entity("CloudLens.API.Models.RemediationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ControlId")
                        .IsRequired();

                    b.Property<string>("CreatedAt")
                        .IsRequired();

                    b.Property<string>("GapDescription")
                        .IsRequired();

                    b.Property<string>("JiraTicketKey");

                    b.Property<string>("JiraTicketUrl");

                    b.Property<string>("Notes")
                        .IsRequired();

                    b.Property<string>("Owner")
                        .IsRequired();

                    b.Property<string>("RemediationSteps")
                        .IsRequired();

                    b.Property<string>("ResolvedAt");

                    b.Property<string>("ResourceId")
                        .IsRequired();

                    b.Property<string>("Severity")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("SubscriptionId")
                        .IsRequired();

                    b.Property<string>("TargetDate")
                        .IsRequired();

                    b.Property<string>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ControlId");

                    b.HasIndex("Status");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("RemediationItems");
                });

            modelBuilder.Entity("CloudLens.API.Models.SocIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedTo");

                    b.Property<int>("CurrentTier");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("DetectedAt");

                    b.Property<int>("EscalationCount");

                    b.Property<string>("IncidentId")
                        .IsRequired();

                    b.Property<string>("JiraTicketKey");

                    b.Property<DateTime?>("LastEscalatedAt");

                    b.Property<string>("Notes")
                        .IsRequired();

                    b.Property<DateTime?>("ResolvedAt");

                    b.Property<string>("ResourceId")
                        .IsRequired();

                    b.Property<string>("ResourceType")
                        .IsRequired();

                    b.Property<int>("Severity");

                    b.Property<string>("SourceAlert")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<string>("SubscriptionId")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CurrentTier");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("IncidentId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SocIncidents");
                });

            modelBuilder.Entity("CloudLens.API.Models.VantaSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiToken")
                        .IsRequired();

                    b.Property<bool>("AutoSyncEnabled");

                    b.Property<bool>("IsEnabled");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("OrganizationId")
                        .IsRequired();

                    b.Property<bool>("SyncCompliance");

                    b.Property<bool>("SyncFinOps");

                    b.Property<int>("SyncIntervalMinutes");

                    b.Property<bool>("SyncResources");

                    b.HasKey("Id");

                    b.HasIndex("LastModified");

                    b.ToTable("VantaSettings");
                });

            modelBuilder.Entity("CloudLens.API.Models.VantaSyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<string>("ErrorMessage");

                    b.Property<int>("EvidenceItemsSynced");

                    b.Property<int>("ResourcesSynced");

                    b.Property<DateTime>("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<string>("SyncType")
                        .IsRequired();

                    b.Property<int>("TestResultsSynced");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("SyncType");

                    b.ToTable("VantaSyncLogs");
                });

            modelBuilder.Entity("CloudLens.API.Models.CostAlertHistory", b =>
                {
                    b.HasOne("CloudLens.API.Models.CostAlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });
#pragma warning restore 612, 618
        }
    }
}
